version: "2" # https://golangci-lint.run/usage/configuration/
linters:
  default: fast
  enable:
    - wsl_v5
  disable:
    - wsl
    - depguard
    # - gochecknoinits
    # - nlreturn
    # - mnd
    # - misspell
    # - inamedparam
    # - gomoddirectives
    - copyloopvar

  settings:
    lll:
      line-length: 160

    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
